apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m
      receiver: 'email alert'
    
    receivers:
    - name: 'email alert'
      email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'devops.ci0cd@gmail.com'
        auth_password: 'eqfnfeygwyzvlvlt'
        from: 'devops.ci0cd@gmail.com'
        to: 'bar-ag@mail.ru'
        headers:
          subject: 'Prometheus Mail Alerts'
