adminUser: admin
adminPassword: admin
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
   - grafana.k8s-1.sa
  path: /
  pathType: Prefix
env:
  GF_SERVER_ROOT_URL: "https://grafana.k8s-1.sa"
  GF_SERVER_DOMAIN: "grafana.k8s-1.sa"
